services:
    doctrine_api_paginator.repository:
        class: Aelfannir\DoctrineApiPaginator\Repositor\ApiServiceEntityRepository
    Aelfannir\DoctrineApiPaginator\Repository\ApiServiceEntityRepository: '@doctrine_api_paginator.repository'